import re

filepath = "lib/core/traductor.dart"

with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

# Text block to append replacing occurrences of `      'agregar_estadistica': 'AGREGAR ESTADÍSTICA PERSONALIZADA',\n    },`

esp_add = """      'agregar_estadistica': 'AGREGAR ESTADÍSTICA PERSONALIZADA',
      'elegir_color': 'ELEGIR COLOR',
      'elegir_diseno': 'ELEGIR DISEÑO',
      'planilla_equipos': 'PLANILLA DE EQUIPOS',
      'equipo_local': 'EQUIPO LOCAL',
      'equipo_visita': 'EQUIPO VISITA',
      'borrar': 'BORRAR',
      'atras': 'ATRÁS',
      'cargar': 'CARGAR',
      'tiempo_amarilla': 'TIEMPO AMARILLA',
      'dos_min': '2 MIN',
      'diez_min': '10 MIN',
      'nuevo_evento': 'NUEVO EVENTO',
      'agregar': 'AGREGAR',
      'iniciar_encuentro': 'INICIAR ENCUENTRO',
      'guardar_parametros': 'GUARDAR PARÁMETROS',
      'parametros_plantilla': 'Parámetros guardados como plantilla',
      'deporte_defecto': 'DEPORTE POR DEFECTO',
      'ajustes_trabajo': 'AJUSTES DE TRABAJO',
      'gestion_datos': 'GESTIÓN DE DATOS',
      'no_hay_partidos_exportar': 'No hay partidos en el historial para exportar',
      'error_exportar': 'Error al exportar',
      'no_hay_plantillas': 'No hay plantillas personalizadas aún.',
      'plantilla_de': 'Plantilla de ',
      'no_hay_partidos_analizar': 'No hay partidos registrados para analizar.',
      'encuentros_por_deporte': 'ENCUENTROS POR DEPORTE',
      'no_hay_encuentros': 'No hay encuentros registrados aún.',
      'resultado_str': 'Resultado: ',
      'identidad_guardada': 'Identidad guardada con éxito',
      'identidad_firma': 'IDENTIDAD Y FIRMA',
      'datos_cronista': 'DATOS DEL CRONISTA / ANALISTA',
      'incluir_firma': 'INCLUIR FIRMA AUTOMÁTICA EN REPORTES',
      'guardar_identidad': 'GUARDAR IDENTIDAD',
      'confirmar_mayus': 'CONFIRMAR',
      'cancelar_mayus': 'CANCELAR',
      'mantenga_presionado': 'Mantén presionado un botón para moverlo',
      'registrar_mayus': 'REGISTRAR',
      'error_exportar_archivo': 'Error al exportar el archivo',
      'reporte_partido': 'REPORTE DEL PARTIDO',
      'bitacora_copiada': 'Bitácora copiada al portapapeles',
      'bitacora_eventos': 'BITÁCORA DE EVENTOS',
      'encuentro_finalizado_bitacora': 'Encuentro finalizado y bitácora generada en Guardados',
      'guardar_mayus': 'GUARDAR',
      'cambio_registrado': 'CAMBIO REGISTRADO',
      'quiere_otro_cambio': '¿Quiere realizar otro cambio en esta misma ventana?',
      'si_mayus': 'SÍ',
      'no_mayus': 'NO',
      'registrar_cambio_extra': 'REGISTRAR CAMBIO EXTRA',
      'num_sale_rojo': 'N° SALE (Rojo)',
      'num_entra_verde': 'N° ENTRA (Verde)',
      'no_hay_registros': 'No hay registros aún.',
      'cerrar_mayus': 'CERRAR',
      'tablero_espacio': 'TABLERO ',
      'reservas_mayus': 'RESERVAS',
      'minuto_a_minuto': 'MINUTO A MINUTO ',
      'registro_dp': 'REGISTRO:',
    },"""

eng_add = """      'agregar_estadistica': 'ADD CUSTOM STATISTIC',
      'elegir_color': 'CHOOSE COLOR',
      'elegir_diseno': 'CHOOSE PATTERN',
      'planilla_equipos': 'TEAM ROSTER',
      'equipo_local': 'HOME TEAM',
      'equipo_visita': 'AWAY TEAM',
      'borrar': 'CLEAR',
      'atras': 'BACK',
      'cargar': 'LOAD',
      'tiempo_amarilla': 'YELLOW CARD TIME',
      'dos_min': '2 MIN',
      'diez_min': '10 MIN',
      'nuevo_evento': 'NEW EVENT',
      'agregar': 'ADD',
      'iniciar_encuentro': 'START MATCH',
      'guardar_parametros': 'SAVE PARAMETERS',
      'parametros_plantilla': 'Parameters saved as template',
      'deporte_defecto': 'DEFAULT SPORT',
      'ajustes_trabajo': 'WORK SETTINGS',
      'gestion_datos': 'DATA MANAGEMENT',
      'no_hay_partidos_exportar': 'No matches in history to export',
      'error_exportar': 'Export error',
      'no_hay_plantillas': 'No custom templates yet.',
      'plantilla_de': 'Template of ',
      'no_hay_partidos_analizar': 'No matches recorded to analyze.',
      'encuentros_por_deporte': 'MATCHES BY SPORT',
      'no_hay_encuentros': 'No matches recorded yet.',
      'resultado_str': 'Result: ',
      'identidad_guardada': 'Identity saved successfully',
      'identidad_firma': 'IDENTITY & SIGNATURE',
      'datos_cronista': 'REPORTER / ANALYST LOGS',
      'incluir_firma': 'AUTO-INCLUDE SIGNATURE',
      'guardar_identidad': 'SAVE IDENTITY',
      'confirmar_mayus': 'CONFIRM',
      'cancelar_mayus': 'CANCEL',
      'mantenga_presionado': 'Hold a button to move it',
      'registrar_mayus': 'RECORD',
      'error_exportar_archivo': 'Error exporting the file',
      'reporte_partido': 'MATCH REPORT',
      'bitacora_copiada': 'Log copied to clipboard',
      'bitacora_eventos': 'EVENT LOG',
      'encuentro_finalizado_bitacora': 'Match ended. Log saved in Records',
      'guardar_mayus': 'SAVE',
      'cambio_registrado': 'SUBSTITUTION RECORDED',
      'quiere_otro_cambio': 'Do you want to record another sub here?',
      'si_mayus': 'YES',
      'no_mayus': 'NO',
      'registrar_cambio_extra': 'RECORD ADDITIONAL SUB',
      'num_sale_rojo': 'N° OUT (RED)',
      'num_entra_verde': 'N° IN (GREEN)',
      'no_hay_registros': 'No records yet.',
      'cerrar_mayus': 'CLOSE',
      'tablero_espacio': 'SCOREBOARD ',
      'reservas_mayus': 'BENCH',
      'minuto_a_minuto': 'PLAY-BY-PLAY ',
      'registro_dp': 'RECORD:',
    },"""

por_add = """      'agregar_estadistica': 'ADICIONAR ESTATÍSTICA',
      'elegir_color': 'ESCOLHER COR',
      'elegir_diseno': 'ESCOLHER DESIGN',
      'planilla_equipos': 'ESCALAÇÕES',
      'equipo_local': 'EQUIPE MANDANTE',
      'equipo_visita': 'EQUIPE VISITANTE',
      'borrar': 'APAGAR',
      'atras': 'VOLTAR',
      'cargar': 'CARREGAR',
      'tiempo_amarilla': 'TEMPO CARTÃO AMARELO',
      'dos_min': '2 MIN',
      'diez_min': '10 MIN',
      'nuevo_evento': 'NOVO EVENTO',
      'agregar': 'ADICIONAR',
      'iniciar_encuentro': 'INICIAR PARTIDA',
      'guardar_parametros': 'SALVAR PARÂMETROS',
      'parametros_plantilla': 'Parâmetros salvos como modelo',
      'deporte_defecto': 'ESPORTE PADRÃO',
      'ajustes_trabajo': 'CONFIGURAÇÕES DE TRABALHO',
      'gestion_datos': 'GESTÃO DE DADOS',
      'no_hay_partidos_exportar': 'Nenhum jogo no histórico',
      'error_exportar': 'Erro ao exportar',
      'no_hay_plantillas': 'Nenhum modelo personalizado ainda.',
      'plantilla_de': 'Modelo de ',
      'no_hay_partidos_analizar': 'Sem partidas para analisar.',
      'encuentros_por_deporte': 'PARTIDAS POR ESPORTE',
      'no_hay_encuentros': 'Nenhuma partida registrada.',
      'resultado_str': 'Resultado: ',
      'identidad_guardada': 'Identidade salva com sucesso',
      'identidad_firma': 'IDENTIDADE E ASSINATURA',
      'datos_cronista': 'DADOS DO REPÓRTER / ANALISTA',
      'incluir_firma': 'INCLUIR ASSINATURA AUTOMATICAMENTE',
      'guardar_identidad': 'SALVAR IDENTIDADE',
      'confirmar_mayus': 'CONFIRMAR',
      'cancelar_mayus': 'CANCELAR',
      'mantenga_presionado': 'Mantenha pressionado para mover',
      'registrar_mayus': 'REGISTRAR',
      'error_exportar_archivo': 'Erro ao exportar o arquivo',
      'reporte_partido': 'RELATÓRIO DA PARTIDA',
      'bitacora_copiada': 'Log copiado para a área de transferência',
      'bitacora_eventos': 'LOG DE EVENTOS',
      'encuentro_finalizado_bitacora': 'Partida encerrada. Log salvo em Partidas Salvas',
      'guardar_mayus': 'SALVAR',
      'cambio_registrado': 'SUBSTITUIÇÃO CADASTRADA',
      'quiere_otro_cambio': 'Deseja realizar outra substituição?',
      'si_mayus': 'SIM',
      'no_mayus': 'NÃO',
      'registrar_cambio_extra': 'REGISTRAR SUBSTITUIÇÃO EXTRA',
      'num_sale_rojo': 'N° SAI (Vermelho)',
      'num_entra_verde': 'N° ENTRA (Verde)',
      'no_hay_registros': 'Nenhum registro ainda.',
      'cerrar_mayus': 'FECHAR',
      'tablero_espacio': 'PLACAR ',
      'reservas_mayus': 'RESERVAS',
      'minuto_a_minuto': 'MINUTO A MINUTO ',
      'registro_dp': 'REGISTRO:',
    },"""

content = content.replace("      'agregar_estadistica': 'AGREGAR ESTADÍSTICA PERSONALIZADA',\n    },", esp_add)
content = content.replace("      'agregar_estadistica': 'ADD CUSTOM STATISTIC',\n    },", eng_add)
content = content.replace("      'agregar_estadistica': 'ADICIONAR ESTATÍSTICA',\n    },", por_add)

with open(filepath, "w", encoding="utf-8") as f:
    f.write(content)

print("Traductor patched")
