// ignore_for_file: prefer_const_constructors, unused_import, prefer_const_literals_to_create_immutables, use_key_in_widget_constructors, deprecated_member_use
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:mi_nueva_app/core/constants.dart';
import 'package:mi_nueva_app/core/globals.dart';
import 'package:mi_nueva_app/core/quantum_storage.dart';

class Traductor {
  static final Map<String, Map<String, String>> _diccionario = {
    'Español': {
      'menu_1': '1 - Iniciar un encuentro',
      'menu_2': '2 - Encuentros Personalizados',
      'menu_3': '3 - Estadísticas',
      'menu_4': '4 - Configuraciones',
      'menu_5': '5 - Mi cuenta',
      'menu_6': '6 - Encuentros guardados',
      'iniciar_mayus': 'INICIAR',
      'en_construccion': 'Sección en construcción',
      'titulo_config': 'CONFIGURACIONES',
      'preferencias': 'PREFERENCIAS',
      'idioma': 'Idioma',
      'idioma_app': 'IDIOMA DE LA APP',
      'Fútbol': 'Fútbol',
      'Rugby': 'Rugby',
      'Basketball': 'Básquet',
      'Baseball': 'Béisbol',
      'Football Americano': 'Fútbol Americano',
      'parametros': 'PARÁMETROS',
      'eventos_reg': 'EVENTOS REGISTRABLES',
      'modo_edicion': 'MODO EDICIÓN HABILITADO',
      'jugadores_colores': 'EQUIPOS Y COLORES',
      'planilla': 'PLANILLA',
      'confirmar': 'OK',
      'editar': 'EDITAR',
      'cancelar': 'CANCELAR',
      'agregar_estadistica': 'AGREGAR ESTADÍSTICA PERSONALIZADA',
      'elegir_color': 'ELEGIR COLOR',
      'elegir_diseno': 'ELEGIR DISEÑO',
      'planilla_equipos': 'PLANILLA DE EQUIPOS',
      'equipo_local': 'EQUIPO LOCAL',
      'equipo_visita': 'EQUIPO VISITA',
      'borrar': 'BORRAR',
      'atras': 'ATRÁS',
      'cargar': 'CARGAR',
      'tiempo_amarilla': 'TIEMPO AMARILLA',
      'dos_min': '2 MIN',
      'diez_min': '10 MIN',
      'nuevo_evento': 'NUEVO EVENTO',
      'agregar': 'AGREGAR',
      'iniciar_encuentro': 'INICIAR ENCUENTRO',
      'guardar_parametros': 'GUARDAR PARÁMETROS',
      'parametros_plantilla': 'Parámetros guardados como plantilla',
      'deporte_defecto': 'DEPORTE POR DEFECTO',
      'ajustes_trabajo': 'AJUSTES DE TRABAJO',
      'gestion_datos': 'GESTIÓN DE DATOS',
      'no_hay_partidos_exportar': 'No hay partidos en el historial para exportar',
      'error_exportar': 'Error al exportar',
      'no_hay_plantillas': 'No hay plantillas personalizadas aún.',
      'plantilla_de': 'Plantilla de ',
      'no_hay_partidos_analizar': 'No hay partidos registrados para analizar.',
      'encuentros_por_deporte': 'ENCUENTROS POR DEPORTE',
      'no_hay_encuentros': 'No hay encuentros registrados aún.',
      'resultado_str': 'Resultado: ',
      'identidad_guardada': 'Identidad guardada con éxito',
      'identidad_firma': 'IDENTIDAD Y FIRMA',
      'datos_cronista': 'DATOS DEL CRONISTA / ANALISTA',
      'incluir_firma': 'INCLUIR FIRMA AUTOMÁTICA EN REPORTES',
      'guardar_identidad': 'GUARDAR IDENTIDAD',
      'confirmar_mayus': 'CONFIRMAR',
      'cancelar_mayus': 'CANCELAR',
      'mantenga_presionado': 'Mantén presionado un botón para moverlo',
      'registrar_mayus': 'REGISTRAR',
      'error_exportar_archivo': 'Error al exportar el archivo',
      'reporte_partido': 'REPORTE DEL PARTIDO',
      'bitacora_copiada': 'Bitácora copiada al portapapeles',
      'bitacora_eventos': 'BITÁCORA DE EVENTOS',
      'encuentro_finalizado_bitacora': 'Encuentro finalizado y bitácora generada en Guardados',
      'guardar_mayus': 'GUARDAR',
      'cambio_registrado': 'CAMBIO REGISTRADO',
      'quiere_otro_cambio': '¿Quiere realizar otro cambio en esta misma ventana?',
      'si_mayus': 'SÍ',
      'no_mayus': 'NO',
      'registrar_cambio_extra': 'REGISTRAR CAMBIO EXTRA',
      'num_sale_rojo': 'N° SALE (Rojo)',
      'num_entra_verde': 'N° ENTRA (Verde)',
      'no_hay_registros': 'No hay registros aún.',
      'cerrar_mayus': 'CERRAR',
      'tablero_espacio': 'TABLERO ',
      'reservas_mayus': 'RESERVAS',
      'minuto_a_minuto': 'MINUTO A MINUTO ',
      'registro_dp': 'REGISTRO:',
      // Nuevos añadidos
      'listas_cargadas': 'Listas Cargadas',
      'no_definidos': 'No definidos',
      'fondo_mayus': 'FONDO',
      'detalle_mayus': 'DETALLE',
      'diseno_mayus': 'DISEÑO',
      'nombre_local_hint': 'Nombre Local...',
      'nombre_visita_hint': 'Nombre Visita...',
      'lista_jugadores_hint': 'Lista Jugadores...',
      'ejemplo_jugadores_hint': 'Ej:\n10 Messi\n9 Benedetto',
      'tu_nombre_apodo': 'Tu Nombre / Apodo',
      'medio_organizacion': 'Medio / Organización (Ej: ESPN, Radio Mitre)',
      'usuario_redes': 'Usuario en Redes (Ej: @MartinDatos)',
      'Tiempos': 'Tiempo',
      'Minutos': 'Minutos',
      'Cambios': 'Cambios',
      'Ventanas': 'Ventanas',
      'Cuartos': 'Cuarto',
      'Tiempos Muertos': 'Tiempos Muertos',
      'Entradas': 'Entrada',
      'Gol': 'Gol',
      'Remates': 'Remates',
      'Remates al arco': 'Remates al arco',
      'Asistencia': 'Asistencia',
      'Corner': 'Corner',
      'Falta': 'Falta',
      'Tarjeta Amarilla': 'Tarjeta Amarilla',
      'Tarjeta Roja': 'Tarjeta Roja',
      'Tarjeta Verde': 'Tarjeta Verde',
      'Cambio': 'Cambio',
      'Try (5 pts)': 'Try (5 pts)',
      'Conversión (2 pts)': 'Conversión (2 pts)',
      'Penal (3 pts)': 'Penal (3 pts)',
      'Drop (3 pts)': 'Drop (3 pts)',
      'Penal': 'Penal',
      'Line Out': 'Line Out',
      'Scrum': 'Scrum',
      'Tiro Libre (1 pt)': 'Tiro Libre (1 pt)',
      'Doble (2 pts)': 'Doble (2 pts)',
      'Triple (3 pts)': 'Triple (3 pts)',
      'Rebotes': 'Rebotes',
      'Tapones': 'Tapones',
      'Falta Personal': 'Falta Personal',
      'Falta Técnica': 'Falta Técnica',
      'Carrera': 'Carrera',
      'Hit': 'Hit',
      'Error': 'Error',
      'Ponche': 'Ponche',
      'Home Run': 'Home Run',
      'Touchdown (6 pts)': 'Touchdown (6 pts)',
      'Field Goal (3 pts)': 'Field Goal (3 pts)',
      'Extra Point (1 pt)': 'Extra Point (1 pt)',
      'Safety (2 pts)': 'Safety (2 pts)',
      'Castigo': 'Castigo',
      'finalizar_periodo_titulo': '¿FINALIZAR ',
      'finalizar_periodo_msj': 'El cronómetro se reiniciará para el próximo período.',
      'siguiente_mayus': 'SIGUIENTE',
      'finalizar_encuentro_titulo': '¿FINALIZAR ENCUENTRO?',
      'finalizar_encuentro_msj': 'Estás en el último período. ¿Deseas terminar el partido y generar el reporte?',
      'terminar_mayus': 'TERMINAR',
      'abandonar_titulo': '¿ABANDONAR SIN GUARDAR?',
      'abandonar_msj': 'Si sales ahora perderás este registro en vivo.',
      'salir_todas_formas': 'SALIR DE TODAS FORMAS',
      'limite_ventanas_titulo': 'LÍMITE DE VENTANAS AGOTADO',
      'limite_ventanas_msj_1': 'El equipo ya no tiene ventanas disponibles (',
      'limite_ventanas_msj_2': '). ¿Continuar de todas formas?',
      'limite_cambios_titulo': 'LÍMITE DE CAMBIOS AGOTADO',
      'limite_cambios_msj_1': 'El equipo ya no tiene cambios disponibles (',
      'limite_cambios_msj_2': '). ¿Continuar de todas formas?',
      'nota_hint': 'Escribí o dictá el comentario del partido acá...',
      'anotar_nota': 'ANOTAR COMENTARIO / NOTA',
      'perfil_ajustes_identidad': 'Configurá tu nombre y firma automática',
      'perfil_ajustes_deporte': 'Elegí con cuál deporte arranca la app',
      'perfil_ajustes_deporte_actual': 'Actual: ',
      'perfil_exportar_db_titulo': 'Exportar Base de Datos',
      'perfil_exportar_db_sub': 'Descargar CSV con todos los encuentros',
      'ninguno': 'Ninguno',
      'titulo_firma_hint': 'Configurá tu identidad',
      'titulo_partido': 'TÍTULO DEL PARTIDO / TORNEO',
      'titulo_partido_hint': 'Ej: Final Champions League...',
      'promedio_posesion': 'POSESIÓN PROMEDIO',
      'victorias': 'VICTORIAS',
      'indicador_disciplina': 'DISCIPLINA (TARJETAS/P)',
      'ritmo_juego': 'INTENSIDAD (ACCIONES/M)',
      'buscar_equipo_hint': 'Buscar equipo o torneo...',
      'top_equipos': 'EQUIPOS MÁS FRECUENTES',
      'sin_datos_filtro': 'No hay datos para este filtro',
      'Base por Bolas': 'Base por Bolas',
      'bateador': 'BATEADOR',
      'lanzador': 'LANZADOR',
      'confirmar_cambio_roles': '¿CONFIRMAR CAMBIO DE ROLES?',
      'diamantes': 'BASES',
      'strikes': 'STRIKES',
      'balls': 'BALLS',
      'outs': 'OUTS',
      'lanzamientos': 'LANZAMIENTOS',
      'orden': 'ORDEN',
      'actualizacion_requerida': 'ACTUALIZACIÓN REQUERIDA',
      'msj_actualizacion': 'Hay una versión crítica disponible. Por favor, actualiza la aplicación para continuar registrando estadísticas con seguridad.',
      'actualizar_ahora': 'ACTUALIZAR AHORA',
      'descargar_en_playstore': 'VER EN GOOGLE PLAY',
      'opciones_finalizar_encuentro': '¿Deseas finalizar el encuentro o ir a tiempo extra?',
      'tiempo_extra_mayus': 'TIEMPO EXTRA',
      'confirmar_finalizar_directo': '¿Seguro que deseas finalizar el encuentro ahora mismo?',
      'nota_mayus': 'NOTA',
      'datos_encuentro': 'DATOS DEL ENCUENTRO',
      'torneo_opcional_hint': 'Torneo (Opcional)',
      'fecha_hint': 'Fecha',
      'titulo_partido_ej_hint': 'Título del Partido (Ej. Final Copa)',
      'equipo_mayus': 'EQUIPO ',
      'pega_lista_hint': 'Pega aquí tu lista... (Ej: 10 Messi)',
      'copia_lista_whatsapp': '¡Copia tu lista de WhatsApp y pégala aquí!',
      'nuevo_partido_de': 'NUEVO PARTIDO DE ',
      'siguiente_reglas': 'SIGUIENTE (REGLAS)',
      // TUTORIAL
      'tut_1_t': '¡BIENVENIDO!',
      'tut_1_d': '¡Bienvenido al Tablero Quantum! 🏟️ Aquí registrarás cada evento del encuentro con máxima velocidad.',
      'tut_2_t': 'EMPIEZA EL PARTIDO',
      'tut_2_d': 'Toca sobre el botón play justo cuando inicie el partido para iniciar/pausar.',
      'tut_3_t': 'SIGUIENTE TIEMPO',
      'tut_3_d': 'Toca el botón Play | para finalizar el periodo y pasar al siguiente.',
      'tut_4_t': '¿ERROR RÁPIDO?',
      'tut_4_d': 'El botón Deshacer elimina la última acción registrada de inmediato.',
      'tut_5_t': 'NOTAS DINÁMICAS',
      'tut_5_d': 'Anota comentarios libres. Mantén presionado para arrastrar este botón a donde te sea más cómodo.',
      'tut_6_t': 'CONTROL DE POSESIÓN',
      'tut_6_d': 'Presiona el botón posesión en cualquier parte para cambiar la posesión de local a visita. Toca pausa para detener el conteo.',
      'tut_7_t': 'FINALIZAR',
      'tut_7_d': 'Cuando el partido termine, toca la bandera para cerrar el encuentro y generar el reporte final.',
      'tut_paso': 'Paso',
      'tut_de': 'de',
      'tut_toca_continuar': 'TOCA PARA CONTINUAR',
      'tut_saltar': 'SALTAR',
      'tut_siguiente': 'SIGUIENTE',
      'reloj_tiro': 'Reloj de Tiro',
      'opciones': 'OPCIONES',
      'editar_salida': 'EDITAR SALIDA',
      'editar_entrada': 'EDITAR ENTRADA',
      'editar_jugador': 'EDITAR JUGADOR',
      'eliminar_registro': 'ELIMINAR REGISTRO',
      'jugador_n_a': 'JUGADOR N/A',
      'anotaciones_mayus': 'ANOTACIONES',
      'tarjetas_mayus': 'TARJETAS',
      'cambios_mayus': 'CAMBIOS',
      'mantenga_presionado_editar': 'MANTÉN PRESIONADO PARA EDITAR',
    },
    'English': {
      'menu_1': '1 - Start a match',
      'menu_2': '2 - Custom Matches',
      'menu_3': '3 - Statistics',
      'menu_4': '4 - Settings',
      'menu_5': '5 - My Account',
      'menu_6': '6 - Saved Matches',
      'iniciar_mayus': 'START',
      'en_construccion': 'Section under construction',
      'titulo_config': 'SETTINGS',
      'preferencias': 'PREFERENCES',
      'idioma': 'Language',
      'idioma_app': 'APP LANGUAGE',
      'Fútbol': 'Soccer',
      'Rugby': 'Rugby',
      'Basketball': 'Basketball',
      'Baseball': 'Baseball',
      'Football Americano': 'American Football',
      'parametros': 'PARAMETERS',
      'eventos_reg': 'TRACKABLE EVENTS',
      'modo_edicion': 'EDIT MODE ENABLED',
      'jugadores_colores': 'TEAMS & COLORS',
      'planilla': 'ROSTER',
      'confirmar': 'CONFIRM',
      'editar': 'EDIT',
      'cancelar': 'CANCEL',
      'agregar_estadistica': 'ADD CUSTOM STATISTIC',
      'elegir_color': 'CHOOSE COLOR',
      'elegir_diseno': 'CHOOSE PATTERN',
      'planilla_equipos': 'TEAM ROSTER',
      'equipo_local': 'HOME TEAM',
      'equipo_visita': 'AWAY TEAM',
      'borrar': 'CLEAR',
      'atras': 'BACK',
      'cargar': 'LOAD',
      'tiempo_amarilla': 'YELLOW CARD TIME',
      'dos_min': '2 MIN',
      'diez_min': '10 MIN',
      'nuevo_evento': 'NEW EVENT',
      'agregar': 'ADD',
      'iniciar_encuentro': 'START MATCH',
      'guardar_parametros': 'SAVE PARAMETERS',
      'parametros_plantilla': 'Parameters saved as template',
      'deporte_defecto': 'DEFAULT SPORT',
      'ajustes_trabajo': 'WORK SETTINGS',
      'gestion_datos': 'DATA MANAGEMENT',
      'no_hay_partidos_exportar': 'No matches in history to export',
      'error_exportar': 'Export error',
      'no_hay_plantillas': 'No custom templates yet.',
      'plantilla_de': 'Template of ',
      'no_hay_partidos_analizar': 'No matches recorded to analyze.',
      'encuentros_por_deporte': 'MATCHES BY SPORT',
      'no_hay_encuentros': 'No matches recorded yet.',
      'resultado_str': 'Result: ',
      'identidad_guardada': 'Identity saved successfully',
      'identidad_firma': 'IDENTITY & SIGNATURE',
      'datos_cronista': 'REPORTER / ANALYST LOGS',
      'incluir_firma': 'AUTO-INCLUDE SIGNATURE',
      'guardar_identidad': 'SAVE IDENTITY',
      'confirmar_mayus': 'CONFIRM',
      'cancelar_mayus': 'CANCEL',
      'mantenga_presionado': 'Hold a button to move it',
      'registrar_mayus': 'RECORD',
      'error_exportar_archivo': 'Error exporting the file',
      'reporte_partido': 'MATCH REPORT',
      'bitacora_copiada': 'Log copied to clipboard',
      'bitacora_eventos': 'EVENT LOG',
      'encuentro_finalizado_bitacora': 'Match ended. Log saved in Records',
      'guardar_mayus': 'SAVE',
      'cambio_registrado': 'SUBSTITUTION RECORDED',
      'quiere_otro_cambio': 'Do you want to record another sub here?',
      'si_mayus': 'YES',
      'no_mayus': 'NO',
      'registrar_cambio_extra': 'RECORD ADDITIONAL SUB',
      'num_sale_rojo': 'N° OUT (RED)',
      'num_entra_verde': 'N° IN (GREEN)',
      'no_hay_registros': 'No records yet.',
      'cerrar_mayus': 'CLOSE',
      'tablero_espacio': 'SCOREBOARD ',
      'reservas_mayus': 'BENCH',
      'minuto_a_minuto': 'PLAY-BY-PLAY ',
      'registro_dp': 'RECORD:',
      // Nuevos añadidos
      'listas_cargadas': 'Lists Loaded',
      'no_definidos': 'Not defined',
      'fondo_mayus': 'BACKGROUND',
      'detalle_mayus': 'DETAIL',
      'diseno_mayus': 'PATTERN',
      'nombre_local_hint': 'Home Team Name...',
      'nombre_visita_hint': 'Away Team Name...',
      'lista_jugadores_hint': 'Player List...',
      'ejemplo_jugadores_hint': 'Ex:\n10 Messi\n9 Benedetto',
      'tu_nombre_apodo': 'Your Name / Nickname',
      'medio_organizacion': 'Media / Org (Ex: ESPN, Local Station)',
      'usuario_redes': 'Social Handles (Ex: @MartinStats)',
      'Tiempos': 'Half',
      'Minutos': 'Minutes',
      'Cambios': 'Substitutions',
      'Ventanas': 'Sub Windows',
      'Cuartos': 'Quarter',
      'Tiempos Muertos': 'Timeouts',
      'Entradas': 'Inning',
      'Gol': 'Goal',
      'Remates': 'Shots',
      'Remates al arco': 'Shots on Target',
      'Asistencia': 'Assist',
      'Corner': 'Corner',
      'Falta': 'Foul',
      'Tarjeta Amarilla': 'Yellow Card',
      'Tarjeta Roja': 'Red Card',
      'Tarjeta Verde': 'Green Card',
      'Cambio': 'Substitution',
      'Try (5 pts)': 'Try (5 pts)',
      'Conversión (2 pts)': 'Conversion (2 pts)',
      'Penal (3 pts)': 'Penalty (3 pts)',
      'Drop (3 pts)': 'Drop (3 pts)',
      'Penal': 'Penalty',
      'Line Out': 'Line Out',
      'Scrum': 'Scrum',
      'Tiro Libre (1 pt)': 'Free Throw (1 pt)',
      'Doble (2 pts)': '2-Pointer',
      'Triple (3 pts)': '3-Pointer',
      'Rebotes': 'Rebounds',
      'Tapones': 'Blocks',
      'Falta Personal': 'Personal Foul',
      'Falta Técnica': 'Technical Foul',
      'Carrera': 'Run',
      'Hit': 'Hit',
      'Error': 'Error',
      'Ponche': 'Strikeout',
      'Home Run': 'Home Run',
      'Touchdown (6 pts)': 'Touchdown (6 pts)',
      'Field Goal (3 pts)': 'Field Goal (3 pts)',
      'Extra Point (1 pt)': 'Extra Point (1 pt)',
      'Safety (2 pts)': 'Safety (2 pts)',
      'Castigo': 'Penalty',
      'finalizar_periodo_titulo': 'FINISH ',
      'finalizar_periodo_msj': 'The timer will reset for the next period.',
      'siguiente_mayus': 'NEXT',
      'finalizar_encuentro_titulo': 'FINISH MATCH?',
      'finalizar_encuentro_msj': 'You are in the final period. Do you want to end the match and generate the report?',
      'terminar_mayus': 'FINISH',
      'abandonar_titulo': 'EXIT WITHOUT SAVING?',
      'abandonar_msj': 'If you exit now, you will lose this live record.',
      'salir_todas_formas': 'EXIT ANYWAY',
      'limite_ventanas_titulo': 'SUB WINDOWS LIMIT REACHED',
      'limite_ventanas_msj_1': 'The team has no substitution windows left (',
      'limite_ventanas_msj_2': '). Continue anyway?',
      'limite_cambios_titulo': 'SUBSTITUTIONS LIMIT REACHED',
      'limite_cambios_msj_1': 'The team has no substitutions left (',
      'limite_cambios_msj_2': '). Continue anyway?',
      'nota_hint': 'Type or dictate the match comment here...',
      'anotar_nota': 'ADD COMMENT / NOTE',
      'perfil_ajustes_identidad': 'Set your name and automatic signature',
      'perfil_ajustes_deporte': 'Choose which sport the app starts with',
      'perfil_ajustes_deporte_actual': 'Current: ',
      'perfil_exportar_db_titulo': 'Export Database',
      'perfil_exportar_db_sub': 'Download CSV with all matches',
      'ninguno': 'None',
      'titulo_firma_hint': 'Configure your identity',
      'titulo_partido': 'MATCH / TOURNAMENT TITLE',
      'titulo_partido_hint': 'Ex: Champions League Final...',
      'promedio_posesion': 'AVERAGE POSSESSION',
      'victorias': 'WIN RATE',
      'indicador_disciplina': 'DISCIPLINE (CARDS/M)',
      'ritmo_juego': 'INTENSITY (ACTIONS/M)',
      'buscar_equipo_hint': 'Search team or tournament...',
      'top_equipos': 'MOST FREQUENT TEAMS',
      'sin_datos_filtro': 'No data for this filter',
      'Base por Bolas': 'Walk',
      'bateador': 'BATTER',
      'lanzador': 'PITCHER',
      'confirmar_cambio_roles': 'CONFIRM ROLE SWAP?',
      'diamantes': 'BASES',
      'strikes': 'STRIKES',
      'balls': 'BALLS',
      'outs': 'OUTS',
      'lanzamientos': 'PITCHES',
      'orden': 'ORDER',
      'actualizacion_requerida': 'UPDATE REQUIRED',
      'msj_actualizacion': 'A critical update is available. Please update the application to continue recording statistics securely.',
      'actualizar_ahora': 'UPDATE NOW',
      'descargar_en_playstore': 'VIEW ON GOOGLE PLAY',
      'opciones_finalizar_encuentro': 'Do you want to end the match or go to extra time?',
      'tiempo_extra_mayus': 'EXTRA TIME',
      'confirmar_finalizar_directo': 'Are you sure you want to end the match right now?',
      'nota_mayus': 'NOTE',
      'datos_encuentro': 'MATCH DATA',
      'torneo_opcional_hint': 'Tournament (Optional)',
      'fecha_hint': 'Date',
      'titulo_partido_ej_hint': 'Match Title (Ex. Cup Final)',
      'equipo_mayus': 'TEAM ',
      'pega_lista_hint': 'Paste your list here... (Ex: 10 Messi)',
      'copia_lista_whatsapp': 'Copy your WhatsApp list and paste it here!',
      'nuevo_partido_de': 'NEW MATCH: ',
      'siguiente_reglas': 'NEXT (RULES)',
      // TUTORIAL
      'tut_1_t': 'WELCOME!',
      'tut_1_d': 'Welcome to the Quantum Dashboard! 🏟️ Here you will record every event of the match with maximum speed.',
      'tut_2_t': 'START THE MATCH',
      'tut_2_d': 'Tap the play button right when the match starts to start/pause.',
      'tut_3_t': 'NEXT PERIOD',
      'tut_3_d': 'Tap the Play | button to end the period and move to the next one.',
      'tut_4_t': 'QUICK ERROR?',
      'tut_4_d': 'The Undo button removes the last recorded action immediately.',
      'tut_5_t': 'DYNAMIC NOTES',
      'tut_5_d': 'Record free comments. Hold to drag this button anywhere you like.',
      'tut_6_t': 'POSSESSION CONTROL',
      'tut_6_d': 'Press the possession button anywhere to switch possession. Tap pause to stop counting.',
      'tut_7_t': 'FINALIZE',
      'tut_7_d': 'When the match ends, tap the flag to close the match and generate the final report.',
      'tut_paso': 'Step',
      'tut_de': 'of',
      'tut_toca_continuar': 'TAP TO CONTINUE',
      'tut_saltar': 'SKIP',
      'tut_siguiente': 'NEXT',
      'reloj_tiro': 'Shot Clock',
      'opciones': 'OPTIONS',
      'editar_salida': 'EDIT OUT',
      'editar_entrada': 'EDIT IN',
      'editar_jugador': 'EDIT PLAYER',
      'eliminar_registro': 'DELETE RECORD',
      'jugador_n_a': 'PLAYER N/A',
      'anotaciones_mayus': 'ANNOTATIONS',
      'tarjetas_mayus': 'CARDS',
      'cambios_mayus': 'SUBSTITUTIONS',
      'mantenga_presionado_editar': 'LONG PRESS TO EDIT',
    },
    'Português': {
      'menu_1': '1 - Iniciar uma partida',
      'menu_2': '2 - Partidas Personalizadas',
      'menu_3': '3 - Estatísticas',
      'menu_4': '4 - Configurações',
      'menu_5': '5 - Minha Conta',
      'menu_6': '6 - Partidas Salvas',
      'iniciar_mayus': 'INICIAR',
      'en_construccion': 'Em construção',
      'titulo_config': 'CONFIGURAÇÕES',
      'preferencias': 'PREFERÊNCIAS',
      'idioma': 'Idioma',
      'idioma_app': 'IDIOMA DO APP',
      'Fútbol': 'Futebol',
      'Rugby': 'Rugby',
      'Basketball': 'Basquete',
      'Baseball': 'Beisebol',
      'Football Americano': 'Futebol Americano',
      'parametros': 'PARÂMETROS',
      'eventos_reg': 'EVENTOS REGISTRÁVEIS',
      'modo_edicion': 'MODO DE EDIÇÃO ATIVADO',
      'jugadores_colores': 'EQUIPES E CORES',
      'planilla': 'ESCALAÇÃO',
      'confirmar': 'OK',
      'editar': 'EDITAR',
      'cancelar': 'CANCELAR',
      'agregar_estadistica': 'ADICIONAR ESTATÍSTICA',
      'elegir_color': 'ESCOLHER COR',
      'elegir_diseno': 'ESCOLHER DESIGN',
      'planilla_equipos': 'ESCALAÇÕES',
      'equipo_local': 'EQUIPE MANDANTE',
      'equipo_visita': 'EQUIPE VISITANTE',
      'borrar': 'APAGAR',
      'atras': 'VOLTAR',
      'cargar': 'CARREGAR',
      'tiempo_amarilla': 'TEMPO CARTÃO AMARELO',
      'dos_min': '2 MIN',
      'diez_min': '10 MIN',
      'nuevo_evento': 'NOVO EVENTO',
      'agregar': 'ADICIONAR',
      'iniciar_encuentro': 'INICIAR PARTIDA',
      'guardar_parametros': 'SALVAR PARÂMETROS',
      'parametros_plantilla': 'Parâmetros salvos como modelo',
      'deporte_defecto': 'ESPORTE PADRÃO',
      'ajustes_trabajo': 'CONFIGURAÇÕES DE TRABALHO',
      'gestion_datos': 'GESTÃO DE DADOS',
      'no_hay_partidos_exportar': 'Nenhum jogo no histórico',
      'error_exportar': 'Erro ao exportar',
      'no_hay_plantillas': 'Nenhum modelo personalizado ainda.',
      'plantilla_de': 'Modelo de ',
      'no_hay_partidos_analizar': 'Sem partidas para analisar.',
      'encuentros_por_deporte': 'PARTIDAS POR ESPORTE',
      'no_hay_encuentros': 'Nenhuma partida registrada.',
      'resultado_str': 'Resultado: ',
      'identidad_guardada': 'Identidade salva com sucesso',
      'identidad_firma': 'IDENTIDADE E ASSINATURA',
      'datos_cronista': 'DADOS DO REPÓRTER / ANALISTA',
      'incluir_firma': 'INCLUIR ASSINATURA AUTOMATICAMENTE',
      'guardar_identidad': 'SALVAR IDENTIDADE',
      'confirmar_mayus': 'CONFIRMAR',
      'cancelar_mayus': 'CANCELAR',
      'mantenga_presionado': 'Mantenha pressionado para mover',
      'registrar_mayus': 'REGISTRAR',
      'error_exportar_archivo': 'Erro ao exportar o arquivo',
      'reporte_partido': 'RELATÓRIO DA PARTIDA',
      'bitacora_copiada': 'Log copiado para a área de transferência',
      'bitacora_eventos': 'LOG DE EVENTOS',
      'encuentro_finalizado_bitacora': 'Partida encerrada. Log salvo em Partidas Salvas',
      'guardar_mayus': 'SALVAR',
      'cambio_registrado': 'SUBSTITUIÇÃO CADASTRADA',
      'quiere_otro_cambio': 'Deseja realizar outra substituição?',
      'si_mayus': 'SIM',
      'no_mayus': 'NÃO',
      'registrar_cambio_extra': 'REGISTRAR SUBSTITUIÇÃO EXTRA',
      'num_sale_rojo': 'N° SAI (Vermelho)',
      'num_entra_verde': 'N° ENTRA (Verde)',
      'no_hay_registros': 'Nenhum registro ainda.',
      'cerrar_mayus': 'FECHAR',
      'tablero_espacio': 'PLACAR ',
      'reservas_mayus': 'RESERVAS',
      'minuto_a_minuto': 'MINUTO A MINUTO ',
      'registro_dp': 'REGISTRO:',
      // Nuevos añadidos
      'listas_cargadas': 'Listas Carregadas',
      'no_definidos': 'Não definidos',
      'fondo_mayus': 'FUNDO',
      'detalle_mayus': 'DETALHE',
      'diseno_mayus': 'PADRÃO',
      'nombre_local_hint': 'Nome do Mandante...',
      'nombre_visita_hint': 'Nome do Visitante...',
      'lista_jugadores_hint': 'Lista de Jogadores...',
      'ejemplo_jugadores_hint': 'Ex:\n10 Messi\n9 Benedetto',
      'tu_nombre_apodo': 'Seu Nome / Apelido',
      'medio_organizacion': 'Veículo / Org (Ex: ESPN, Rádio Local)',
      'usuario_redes': 'Usuário em Redes (Ex: @MartinStats)',
      'Tiempos': 'Tempo',
      'Minutos': 'Minutos',
      'Cambios': 'Substituições',
      'Ventanas': 'Janelas',
      'Cuartos': 'Quarto',
      'Tiempos Muertos': 'Pedidos de Tempo',
      'Entradas': 'Entrada',
      'Gol': 'Gol',
      'Remates': 'Finalizações',
      'Remates al arco': 'Chutes a Gol',
      'Asistencia': 'Assistência',
      'Corner': 'Escanteio',
      'Falta': 'Falta',
      'Tarjeta Amarilla': 'Cartão Amarelo',
      'Tarjeta Roja': 'Cartão Vermelho',
      'Tarjeta Verde': 'Cartão Verde',
      'Cambio': 'Substituição',
      'Try (5 pts)': 'Try (5 pts)',
      'Conversión (2 pts)': 'Conversão (2 pts)',
      'Penal (3 pts)': 'Pênalti (3 pts)',
      'Drop (3 pts)': 'Drop (3 pts)',
      'Penal': 'Pênalti',
      'Line Out': 'Line Out',
      'Scrum': 'Scrum',
      'Tiro Libre (1 pt)': 'Lance Livre (1 pt)',
      'Doble (2 pts)': 'Cesta de 2',
      'Triple (3 pts)': 'Cesta de 3',
      'Rebotes': 'Rebotes',
      'Tapones': 'Tocos',
      'Falta Personal': 'Falta Pessoal',
      'Falta Técnica': 'Falta Técnica',
      'Carrera': 'Corrida',
      'Hit': 'Hit',
      'Error': 'Erro',
      'Ponche': 'Strikeout',
      'Home Run': 'Home Run',
      'Touchdown (6 pts)': 'Touchdown (6 pts)',
      'Field Goal (3 pts)': 'Field Goal (3 pts)',
      'Extra Point (1 pt)': 'Extra Point (1 pt)',
      'Safety (2 pts)': 'Safety (2 pts)',
      'Castigo': 'Falta',
      'finalizar_periodo_titulo': 'FINALIZAR ',
      'finalizar_periodo_msj': 'O cronômetro será zerado para o próximo período.',
      'siguiente_mayus': 'PRÓXIMO',
      'finalizar_encuentro_titulo': 'FINALIZAR PARTIDA?',
      'finalizar_encuentro_msj': 'Você está no último período. Deseja encerrar a partida e gerar o relatório?',
      'terminar_mayus': 'TERMINAR',
      'abandonar_titulo': 'SAIR SEM SALVAR?',
      'abandonar_msj': 'Se você sair agora, perderá este registro ao vivo.',
      'salir_todas_formas': 'SAIR MESMO ASSIM',
      'limite_ventanas_titulo': 'LIMITE DE JANELAS ATINGIDO',
      'limite_ventanas_msj_1': 'A equipe não tem mais janelas disponíveis (',
      'limite_ventanas_msj_2': '). Continuar mesmo assim?',
      'limite_cambios_titulo': 'LIMITE DE SUBSTITUIÇÕES ATINGIDO',
      'limite_cambios_msj_1': 'A equipe não tem mais substituições disponíveis (',
      'limite_cambios_msj_2': '). Continuar mesmo assim?',
      'nota_hint': 'Escreva ou dite o comentário da partida aqui...',
      'anotar_nota': 'ANOTAR COMENTÁRIO / NOTA',
      'perfil_ajustes_identidad': 'Configure seu nome e assinatura automática',
      'perfil_ajustes_deporte': 'Escolha com qual esporte o app inicia',
      'perfil_ajustes_deporte_actual': 'Atual: ',
      'perfil_exportar_db_titulo': 'Exportar Banco de Dados',
      'perfil_exportar_db_sub': 'Baixar CSV com todas as partidas',
      'ninguno': 'Nenhum',
      'titulo_firma_hint': 'Configure sua identidade',
      'actualizacion_requerida': 'ATUALIZAÇÃO NECESSÁRIA',
      'msj_actualizacion': 'Uma atualização crítica está disponível. Por favor, atualize o aplicativo para continuar registrando estatísticas com segurança.',
      'actualizar_ahora': 'ATUALIZAR AGORA',
      'descargar_en_playstore': 'VER NA GOOGLE PLAY',
      'Base por Bolas': 'Base por Bolas',
      'bateador': 'BATEDOR',
      'lanzador': 'LANÇADOR',
      'confirmar_cambio_roles': 'CONFIRMAR TROCA DE FUNÇÕES?',
      'diamantes': 'BASES',
      'strikes': 'STRIKES',
      'balls': 'BALLS',
      'outs': 'OUTS',
      'lanzamientos': 'ARREMESSOS',
      'orden': 'ORDEM',
      'opciones_finalizar_encuentro': 'Deseja encerrar a partida ou ir para a prorrogação?',
      'tiempo_extra_mayus': 'TEMPO EXTRA',
      'confirmar_finalizar_directo': 'Tem certeza de que deseja encerrar a partida agora mesmo?',
      'nota_mayus': 'NOTA',
      'datos_encuentro': 'DADOS DA PARTIDA',
      'torneo_opcional_hint': 'Torneio (Opcional)',
      'fecha_hint': 'Data',
      'titulo_partido_ej_hint': 'Título da Partida (Ex. Final da Copa)',
      'equipo_mayus': 'EQUIPE ',
      'pega_lista_hint': 'Cole sua lista aqui... (Ex: 10 Messi)',
      'copia_lista_whatsapp': 'Copie sua lista do WhatsApp e cole aqui!',
      'nuevo_partido_de': 'NOVA PARTIDA DE ',
      'siguiente_reglas': 'PRÓXIMO (REGRAS)',
      // TUTORIAL
      'tut_1_t': 'BEM-VINDO!',
      'tut_1_d': 'Bem-vindo ao Painel Quantum! 🏟️ Aqui você registrará cada evento da partida com velocidade máxima.',
      'tut_2_t': 'COMEÇA A PARTIDA',
      'tut_2_d': 'Toque no botão play assim que a partida começar para iniciar/pausar.',
      'tut_3_t': 'PRÓXIMO TEMPO',
      'tut_3_d': 'Toque no botão Play | para encerrar o período e passar para o próximo.',
      'tut_4_t': 'ERRO RÁPIDO?',
      'tut_4_d': 'O botão Desfazer remove a última ação registrada imediatamente.',
      'tut_5_t': 'NOTAS DINÂMICAS',
      'tut_5_d': 'Anote comentários livres. Mantenha pressionado para arrastar este botão para onde for mais confortável.',
      'tut_6_t': 'CONTROLE DE POSSE',
      'tut_6_d': 'Pressione o botão de posse em qualquer lugar para alternar a posse. Toque em pausa para parar a contagem.',
      'tut_7_t': 'FINALIZAR',
      'tut_7_d': 'Quando a partida terminar, toque na bandeira para encerrar o encontro e gerar o relatório final.',
      'tut_paso': 'Passo',
      'tut_de': 'de',
      'tut_toca_continuar': 'TOQUE PARA CONTINUAR',
      'tut_saltar': 'PULAR',
      'tut_siguiente': 'PRÓXIMO',
      'reloj_tiro': 'Relógio de Posse',
    }
  };

  static String get(String clave) {
    String idiomaActual = perfilUsuario['idioma'] ?? 'Español';
    return _diccionario[idiomaActual]?[clave] ?? clave;
  }
}
